name: Schedule

on:
  workflow_dispatch: {}
  schedule:
    # UTC time 00:00 every day
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - run: pnpm install --frozen-lockfile
      - run: pnpm run generate

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update data'
          commit_options: --no-verify --signoff
          file_pattern: .
          commit_author: Author <actions@github.com>

  deploy:
    runs-on: ubuntu-latest
    needs: [generate]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:site

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
