name: Schedule

on:
  workflow_dispatch: {}
  schedule:
    # UTC time 00:00 every day
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - run: pnpm install --frozen-lockfile
      - run: pnpm run generate

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update data'
          commit_options: --no-verify --signoff
          file_pattern: .
          commit_author: Author <actions@github.com>
